spring:
  web:
    locale-resolver: fixed
    locale: pt_BR

  sql:
    init:
      mode: never

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testDevJunior?createDatabaseIfNotExist=true&useSSL=false&allowPubliclyRetrieval=true&serverTimeZone=America/Sao_Paulo
    username: root
    password: sucesso

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  main:
    allow-circular-references: true